name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
